//! Agent Key Delegation
//!
//! Enables gasless trading via delegated signing.
//! Users sign once with MetaMask to authorize an agent key,
//! then the agent key can sign orders without wallet popups.

use std::time::{SystemTime, UNIX_EPOCH};

use alloy_primitives::{keccak256, Address, B256, U256};
use serde::{Deserialize, Serialize};

use super::eip712::{EIP712Domain, EIP712Signer, OrderEIP712};
use super::signer::{recover_address, Signer, SignerError};

/// Agent delegation (permission for agent to trade on behalf of wallet)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentDelegation {
    /// Main wallet address (e.g., MetaMask)
    pub wallet: Address,
    /// Agent key address (generated by frontend)
    pub agent: Address,
    /// Unix timestamp when delegation expires
    pub expiration: u64,
    /// Nonce for replay protection
    pub nonce: U256,
}

impl AgentDelegation {
    /// Check if delegation has expired using wall clock time
    ///
    /// WARNING: This method uses SystemTime::now() which can cause
    /// non-determinism across validators due to clock skew.
    /// Use `is_expired_at()` with block timestamp for consensus-critical code.
    #[allow(dead_code)]
    pub fn is_expired(&self) -> bool {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs();
        self.expiration < now
    }

    /// Check if delegation has expired at a given timestamp
    ///
    /// This is the preferred method for consensus-critical code.
    /// Use the block timestamp to ensure determinism across validators.
    pub fn is_expired_at(&self, block_timestamp_ms: u64) -> bool {
        // Convert block timestamp from milliseconds to seconds
        let timestamp_secs = block_timestamp_ms / 1000;
        self.expiration < timestamp_secs
    }

    /// Compute the struct hash for this delegation
    pub fn struct_hash(&self) -> B256 {
        let type_hash = keccak256(
            b"AgentDelegation(address wallet,address agent,uint256 expiration,uint256 nonce)"
        );

        let mut encoded = Vec::new();
        encoded.extend_from_slice(type_hash.as_slice());
        encoded.extend_from_slice(&[0u8; 12]); // address padding
        encoded.extend_from_slice(self.wallet.as_slice());
        encoded.extend_from_slice(&[0u8; 12]);
        encoded.extend_from_slice(self.agent.as_slice());
        encoded.extend_from_slice(&U256::from(self.expiration).to_be_bytes::<32>());
        encoded.extend_from_slice(&self.nonce.to_be_bytes::<32>());

        keccak256(&encoded)
    }
}

/// Agent signer for delegations
pub struct AgentSigner {
    domain: EIP712Domain,
}

impl AgentSigner {
    /// Create a new signer with the given domain
    pub fn new(domain: EIP712Domain) -> Self {
        Self { domain }
    }

    /// Create a signer with the default domain
    pub fn default_domain() -> Self {
        Self::new(EIP712Domain::default())
    }

    /// Hash a delegation according to EIP-712
    pub fn hash_delegation(&self, delegation: &AgentDelegation) -> B256 {
        let domain_separator = self.domain.separator();
        let struct_hash = delegation.struct_hash();

        let mut message = vec![0x19, 0x01];
        message.extend_from_slice(domain_separator.as_slice());
        message.extend_from_slice(struct_hash.as_slice());

        keccak256(&message)
    }

    /// Sign a delegation with wallet key
    pub fn sign_delegation(&self, wallet_signer: &Signer, delegation: &AgentDelegation) -> [u8; 65] {
        let hash = self.hash_delegation(delegation);
        wallet_signer.sign(&hash.into())
    }

    /// Verify a delegation signature
    pub fn verify_delegation(
        &self,
        delegation: &AgentDelegation,
        signature: &[u8],
    ) -> Result<bool, SignerError> {
        let hash = self.hash_delegation(delegation);
        let recovered = recover_address(&hash.into(), signature)?;
        Ok(recovered == delegation.wallet)
    }

    /// Generate typed data JSON for MetaMask
    pub fn delegation_to_json(&self, delegation: &AgentDelegation) -> serde_json::Value {
        serde_json::json!({
            "types": {
                "EIP712Domain": [
                    {"name": "name", "type": "string"},
                    {"name": "version", "type": "string"},
                    {"name": "chainId", "type": "uint256"},
                    {"name": "verifyingContract", "type": "address"}
                ],
                "AgentDelegation": [
                    {"name": "wallet", "type": "address"},
                    {"name": "agent", "type": "address"},
                    {"name": "expiration", "type": "uint256"},
                    {"name": "nonce", "type": "uint256"}
                ]
            },
            "primaryType": "AgentDelegation",
            "domain": {
                "name": self.domain.name,
                "version": self.domain.version,
                "chainId": self.domain.chain_id.to_string(),
                "verifyingContract": self.domain.verifying_contract.to_string()
            },
            "message": {
                "wallet": delegation.wallet.to_string(),
                "agent": delegation.agent.to_string(),
                "expiration": delegation.expiration.to_string(),
                "nonce": delegation.nonce.to_string()
            }
        })
    }
}

/// Verify an order signed by an agent key
///
/// Checks:
/// 1. Agent signature is valid
/// 2. Delegation exists and is not expired (using block timestamp)
/// 3. Delegation signature is valid
/// 4. Order owner matches delegation wallet
///
/// Parameters:
/// - `block_timestamp_ms`: Block timestamp in milliseconds for deterministic expiration check
pub fn verify_agent_order(
    order: &OrderEIP712,
    agent_signature: &[u8],
    delegation: &AgentDelegation,
    delegation_signature: &[u8],
    eip712_signer: &EIP712Signer,
    agent_signer: &AgentSigner,
    block_timestamp_ms: u64,
) -> Result<bool, AgentError> {
    // Step 1: Verify agent signed the order
    let order_hash = eip712_signer.hash_order(order);
    let agent_addr = recover_address(&order_hash.into(), agent_signature)
        .map_err(|e| AgentError::SignatureError(e.to_string()))?;

    if agent_addr != delegation.agent {
        return Err(AgentError::AgentMismatch {
            expected: delegation.agent,
            got: agent_addr,
        });
    }

    // Step 2: Verify delegation is not expired (using block timestamp for determinism)
    if delegation.is_expired_at(block_timestamp_ms) {
        return Err(AgentError::DelegationExpired(delegation.expiration));
    }

    // Step 3: Verify wallet signed the delegation
    let valid = agent_signer
        .verify_delegation(delegation, delegation_signature)
        .map_err(|e| AgentError::SignatureError(e.to_string()))?;

    if !valid {
        return Err(AgentError::InvalidDelegation);
    }

    // Step 4: Verify order owner matches delegation wallet
    if order.owner != delegation.wallet {
        return Err(AgentError::OwnerMismatch {
            order_owner: order.owner,
            delegation_wallet: delegation.wallet,
        });
    }

    Ok(true)
}

/// Agent-related errors
#[derive(Debug, Clone, thiserror::Error)]
pub enum AgentError {
    #[error("signature error: {0}")]
    SignatureError(String),
    #[error("agent mismatch: expected {expected}, got {got}")]
    AgentMismatch { expected: Address, got: Address },
    #[error("delegation expired at {0}")]
    DelegationExpired(u64),
    #[error("invalid delegation signature")]
    InvalidDelegation,
    #[error("owner mismatch: order owner {order_owner} != delegation wallet {delegation_wallet}")]
    OwnerMismatch {
        order_owner: Address,
        delegation_wallet: Address,
    },
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;

    #[test]
    fn test_delegation_flow() {
        // Step 1: User's wallet
        let wallet = Signer::generate();

        // Step 2: Frontend generates agent key
        let agent = Signer::generate();

        // Step 3: Create delegation (expires in 1 hour)
        let now_secs = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs();
        let expiration = now_secs + 3600;

        let delegation = AgentDelegation {
            wallet: wallet.address(),
            agent: agent.address(),
            expiration,
            nonce: U256::from(1),
        };

        // Step 4: Wallet signs delegation
        let agent_signer = AgentSigner::default_domain();
        let delegation_sig = agent_signer.sign_delegation(&wallet, &delegation);

        // Step 5: Verify delegation
        let valid = agent_signer.verify_delegation(&delegation, &delegation_sig).unwrap();
        assert!(valid);

        // Step 6: Agent signs order (on behalf of wallet)
        let order = OrderEIP712 {
            symbol: "BTC-USDT".to_string(),
            side: 1,
            order_type: 1,
            price: U256::from(50000),
            qty: U256::from(100),
            nonce: U256::from(1),
            deadline: U256::ZERO,
            leverage: 10,
            owner: wallet.address(), // Owner is still wallet
        };

        let eip712_signer = EIP712Signer::default_domain();
        let order_sig = eip712_signer.sign_order(&agent, &order); // Agent signs!

        // Step 7: Verify agent order (using block timestamp in milliseconds)
        let block_timestamp_ms = now_secs * 1000; // Current time as block timestamp
        let valid = verify_agent_order(
            &order,
            &order_sig,
            &delegation,
            &delegation_sig,
            &eip712_signer,
            &agent_signer,
            block_timestamp_ms,
        )
        .unwrap();

        assert!(valid);
    }

    #[test]
    fn test_expired_delegation() {
        let wallet = Signer::generate();
        let agent = Signer::generate();

        // Expired delegation (expired at timestamp 100 seconds)
        let delegation = AgentDelegation {
            wallet: wallet.address(),
            agent: agent.address(),
            expiration: 100, // Expires at 100 seconds
            nonce: U256::from(1),
        };

        // Test is_expired_at with block timestamp
        assert!(delegation.is_expired_at(200_000)); // 200 seconds in ms > 100s expiration
        assert!(!delegation.is_expired_at(50_000));  // 50 seconds in ms < 100s expiration

        let agent_signer = AgentSigner::default_domain();
        let delegation_sig = agent_signer.sign_delegation(&wallet, &delegation);

        let order = OrderEIP712 {
            symbol: "BTC-USDT".to_string(),
            side: 1,
            order_type: 1,
            price: U256::from(50000),
            qty: U256::from(100),
            nonce: U256::from(1),
            deadline: U256::ZERO,
            leverage: 10,
            owner: wallet.address(),
        };

        let eip712_signer = EIP712Signer::default_domain();
        let order_sig = eip712_signer.sign_order(&agent, &order);

        // Verify fails with block timestamp after expiration
        let result = verify_agent_order(
            &order,
            &order_sig,
            &delegation,
            &delegation_sig,
            &eip712_signer,
            &agent_signer,
            200_000, // Block timestamp: 200 seconds (after expiration)
        );

        assert!(matches!(result, Err(AgentError::DelegationExpired(_))));

        // Verify succeeds with block timestamp before expiration
        let result = verify_agent_order(
            &order,
            &order_sig,
            &delegation,
            &delegation_sig,
            &eip712_signer,
            &agent_signer,
            50_000, // Block timestamp: 50 seconds (before expiration)
        );

        assert!(result.is_ok());
    }
}
